server:
  port: 8080

spring:
  #Databaase配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

  #Jpa配置
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  #Liquibase配置
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.yaml

  #Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 5000ms
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 2

#Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.carrx.demo.middleware.entityUnderscoreToCamelCase
  configuration:
    map-underscore-to-camel-case: true

demo:
  page:
    maxPageSize: 2000
    pageNum: 1
    pageSize: 20